Repository INRIA/spoon, pull requests merged in 2024-01, with the labels that each got.

#5611 doc: Fix jekyll rendering of spoon_javadoc.md
  doc/spoon_javadoc.md
Labels: documentation

#5615 review: chore: Update nix lockfile
  flake.lock
Labels: chore

#5621 fix: Add thread-safety to TypeAdaptor method adaptation
  src/main/java/spoon/support/adaption/TypeAdaptor.java
Labels: bug
